networks:
  hostheader_net:
    driver: bridge


services:
  haproxy:
    image: haproxy:2.9
    container_name: haproxy
    ports:
      - "8080:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - web1
      - web2
    networks:
      - hostheader_net


  web1:
    image: nginx:alpine
    container_name: web1
    volumes:
      - ./web1/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - hostheader_net

  web2:
    image: nginx:alpine
    container_name: web2
    volumes:
      - ./web2/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - hostheader_net

