services:
  redis-node-7000:
    image: redis:7
    container_name: redis-node-7000
    command: redis-server --port 7000 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7000:7000"
    networks:
      - redis-cluster-net
    volumes:
      - ./redis-data-7000:/data

  redis-node-7001:
    image: redis:7
    container_name: redis-node-7001
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:7001"
    networks:
      - redis-cluster-net
    volumes:
      - ./redis-data-7001:/data

  redis-node-7002:
    image: redis:7
    container_name: redis-node-7002
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:7002"
    networks:
      - redis-cluster-net
    volumes:
      - ./redis-data-7002:/data

  redis-node-7003:
    image: redis:7
    container_name: redis-node-7003
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:7003"
    networks:
      - redis-cluster-net
    volumes:
      - ./redis-data-7003:/data

  redis-node-7004:
    image: redis:7
    container_name: redis-node-7004
    command: redis-server --port 7004 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7004:7004"
    networks:
      - redis-cluster-net
    volumes:
      - ./redis-data-7004:/data

  redis-node-7005:
    image: redis:7
    container_name: redis-node-7005
    command: redis-server --port 7005 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7005:7005"
    networks:
      - redis-cluster-net
    volumes:
      - ./redis-data-7005:/data

networks:
  redis-cluster-net:
