services:
  node1:
    build: .
    container_name: node1
    hostname: node1
    networks:
      ubuntu-net:
    tty: true
    stdin_open: true
    privileged: true

  node2:
    build: .
    container_name: node2
    hostname: node2
    networks:
      ubuntu-net:
    tty: true
    stdin_open: true
    privileged: true

  node3:
    build: .
    container_name: node3
    hostname: node3
    networks:
      ubuntu-net:
    tty: true
    stdin_open: true
    privileged: true

  node4:
    build: .
    container_name: node4
    hostname: node4
    networks:
      ubuntu-net:
    tty: true
    stdin_open: true
    privileged: true

  node5:
    build: .
    container_name: node5
    hostname: node5
    networks:
      ubuntu-net:
    tty: true
    stdin_open: true
    privileged: true

networks:
  ubuntu-net:
    driver: bridge
