services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start
      - --https-port=8443
      - --https-key-store-file=/opt/keycloak/conf/keycloak.jks
      - --https-key-store-password=password
      - --https-key-store-type=JKS
      - --hostname=localhost
    ports:
      - "8443:8443"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: dev-mem
    volumes:
      - ./keycloak.jks:/opt/keycloak/conf/keycloak.jks
