services:
  myalpine1:
    image: alpine:latest
    container_name: myalpine1
    hostname: myalpine1
    privileged: true
    command: sh -c "apk update && apk add iptables tcpdump && sleep 24h"  # Install iptables, tcpdump and keep the container running
    networks:
      - demo-network  # Optional: custom network if required

  myalpine2:
    image: alpine:latest
    container_name: myalpine2
    hostname: myalpine2
    user: root
    privileged: true
    command: sh -c "apk update && apk add iptables tcpdump && sleep 24h"  # Install iptables, tcpdump and keep the container running
    networks:
      - demo-network  # Optional: custom network if required

  myalpine3:
    image: alpine:latest
    container_name: myalpine3
    hostname: myalpine3
    user: root
    privileged: true
    command: sh -c "apk update && apk add iptables tcpdump && sleep 24h"  # Install iptables, tcpdump and keep the container running
    networks:
      - demo-network  # Optional: custom network if required

networks:
  demo-network:
    driver: bridge  # Default driver
